[package]
name = "axruntime"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "Runtime library of ArceOS"
license = "GPL-3.0-or-later OR Apache-2.0"
homepage = "https://github.com/rcore-os/arceos"
repository = "https://github.com/rcore-os/arceos/tree/main/modules/axruntime"
documentation = "https://rcore-os.github.io/arceos/axruntime/index.html"

[features]
alloc = ["dep:axalloc"]
paging = ["alloc", "axhal/paging", "dep:lazy_init"]
multitask = ["alloc", "axtask/multitask"]
smp = ["axhal/smp", "spinlock/smp"]

fs = ["alloc", "paging", "axdriver/virtio-blk", "axfs/use-virtio-blk"] # TODO: remove "paging"
net = ["alloc", "paging", "axdriver/virtio-net", "dep:axnet"]
display = ["alloc", "paging", "axdriver/virtio-gpu", "dep:axdisplay"]

default = ["axtask?/default"]

[dependencies]
percpu = { path = "../../crates/percpu" }
kernel_guard = { path = "../../crates/kernel_guard" }
spinlock = { path = "../../crates/spinlock" }
lazy_init = { path = "../../crates/lazy_init", optional = true }
crate_interface = { path = "../../crates/crate_interface" }
axalloc = { path = "../axalloc", optional = true }
axconfig = { path = "../axconfig" }
axdriver = { path = "../axdriver", optional = true }
axhal = { path = "../axhal" }
axlog = { path = "../axlog" }
axfs = { path = "../axfs", optional = true }
axnet = { path = "../axnet", optional = true }
axdisplay = { path = "../axdisplay", optional = true }
axtask = { path = "../axtask", default-features = false, optional = true }
