[package]
name = "axruntime"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
alloc = ["dep:axalloc"]
paging = ["alloc", "axhal/paging"]
multitask = ["alloc", "axtask/multitask"]

fs = ["alloc", "paging", "axdriver/virtio-blk"] # TODO: remove "paging"
net = ["alloc", "paging", "axdriver/virtio-net", "dep:axnet"]

log-level-off = ["axlog/log-level-off"]
log-level-error = ["axlog/log-level-error"]
log-level-warn = ["axlog/log-level-warn"]
log-level-info = ["axlog/log-level-info"]
log-level-debug = ["axlog/log-level-debug"]
log-level-trace = ["axlog/log-level-trace"]

platform-qemu-virt-riscv = ["axhal/platform-qemu-virt-riscv", "axdriver?/bus-mmio"]
platform-qemu-virt-aarch64 = ["axhal/platform-qemu-virt-aarch64", "axdriver?/bus-mmio"]

default = []

[dependencies]
axalloc = { path = "../axalloc", optional = true }
axconfig = { path = "../axconfig" }
axdriver = { path = "../axdriver", optional = true }
axhal = { path = "../axhal" }
axlog = { path = "../axlog" }
axnet = { path = "../axnet", optional = true }
axtask = { path = "../axtask", optional = true }
