[package]
name = "axruntime"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
alloc = ["dep:axalloc"]
paging = ["alloc", "axhal/paging"]
multitask = ["alloc", "axtask/multitask"]
smp = ["axhal/smp", "spinlock/smp"]

fs = ["alloc", "paging", "axdriver/virtio-blk"] # TODO: remove "paging"
net = ["alloc", "paging", "axdriver/virtio-net", "dep:axnet"]
display = ["alloc", "paging", "axdriver/virtio-gpu", "dep:axdisplay"]

default = []

[dependencies]
spinlock = { path = "../../crates/spinlock" }
crate_interface = { path = "../../crates/crate_interface" }
axalloc = { path = "../axalloc", optional = true }
axconfig = { path = "../axconfig" }
axdriver = { path = "../axdriver", optional = true }
axhal = { path = "../axhal" }
axlog = { path = "../axlog" }
axnet = { path = "../axnet", optional = true }
axdisplay = { path = "../axdisplay", optional = true }
axtask = { path = "../axtask", default-features = false }
