[package]
name = "task_single_yield"
version = "0.1.0"
edition = "2021"
authors = ["Youjie Zheng <zyj578335934@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
axstd = { path = "../../../ulib/axstd", features = ["multitask", "alloc"], optional = true }