[package]
name = "percpu"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "Define and access per-CPU data structures"
license = "GPL-3.0-or-later OR Apache-2.0"
homepage = "https://github.com/rcore-os/arceos"
repository = "https://github.com/rcore-os/arceos/tree/main/crates/percpu"
documentation = "https://rcore-os.github.io/arceos/percpu/index.html"

[features]
# For single CPU use, just make the per-CPU data a global variable.
sp-naive = ["percpu_macros/sp-naive"]

# Whether the system enables preemption.
preempt = ["percpu_macros/preempt", "dep:kernel_guard"]

default = []

[dependencies]
cfg-if = "1.0"
kernel_guard = { path = "../kernel_guard", optional = true }
percpu_macros = { path = "../percpu_macros" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86 = "0.52"

[target.'cfg(not(target_os = "none"))'.dependencies]
spin = "0.9"
