[package]
name = "axprocess"
version = "0.1.0"
edition = "2021"
authors = ["Youjie Zheng <zyj578335934@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spinlock = { path = "../../crates/spinlock" }
axtask = { path = "../axtask" }
axhal = { path = "../axhal" }
axlog = { path = "../axlog" }
axmem = { path = "../axmem" }
axfs_os = { path = "../axfs_os" }
riscv = "0.10"
bitflags = "= 2.1.0"