[package]
name = "axstd"
version.workspace = true
edition.workspace = true
authors = [
    "Yuekai Jia <equation618@gmail.com>",
    "yanjuguang <coolyanjg@163.com>",
    "wudashuai <wu-ds20@mails.tsinghua.edu.cn>",
    "yfblock <321353225@qq.com>",
    "scPointer <bhy18@mails.tsinghua.edu.cn>",
    "Shiping Yuan <robert_yuan@pku.edu.com>",
]
description = "ArceOS user library with an interface similar to rust std"
license.workspace = true
homepage.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/ulib/axstd"
documentation = "https://arceos-org.github.io/arceos/axstd/index.html"

[features]
default = []

# Multicore
smp = ["axfeat/smp", "kspin/smp"]

# Floating point/SIMD
fp-simd = ["axfeat/fp-simd"]

# Interrupts
irq = ["arceos_api/irq", "axfeat/irq"]

# Memory
alloc = ["arceos_api/alloc", "axfeat/alloc", "axio/alloc"]
alloc-tlsf = ["axfeat/alloc-tlsf"]
alloc-slab = ["axfeat/alloc-slab"]
alloc-buddy = ["axfeat/alloc-buddy"]
page-alloc-64g = ["axfeat/page-alloc-64g"] # Support up to 64G memory capacity
page-alloc-4g = ["axfeat/page-alloc-4g"] # Support up to 4G memory capacity
paging = ["axfeat/paging"]
dma = ["arceos_api/dma", "axfeat/dma"]
tls = ["axfeat/tls"]

# Multi-threading and scheduler
multitask = ["arceos_api/multitask", "axfeat/multitask"]
sched-fifo = ["axfeat/sched-fifo"]
sched-rr = ["axfeat/sched-rr"]
sched-cfs = ["axfeat/sched-cfs"]

# File system
fs = ["arceos_api/fs", "axfeat/fs"]
myfs = ["arceos_api/myfs", "axfeat/myfs"]

# Networking
net = ["arceos_api/net", "axfeat/net"]
dns = []

# Display
display = ["arceos_api/display", "axfeat/display"]

# Real Time Clock (RTC) Driver.
rtc = ["axfeat/rtc"]

# Device drivers
bus-mmio = ["axfeat/bus-mmio"]
bus-pci = ["axfeat/bus-pci"]
driver-ramdisk = ["axfeat/driver-ramdisk"]
driver-ixgbe = ["axfeat/driver-ixgbe"]
driver-fxmac = ["axfeat/driver-fxmac"]
driver-bcm2835-sdhci = ["axfeat/driver-bcm2835-sdhci"]

# Logging
log-level-off = ["axfeat/log-level-off"]
log-level-error = ["axfeat/log-level-error"]
log-level-warn = ["axfeat/log-level-warn"]
log-level-info = ["axfeat/log-level-info"]
log-level-debug = ["axfeat/log-level-debug"]
log-level-trace = ["axfeat/log-level-trace"]

[dependencies]
axfeat = { workspace = true }
arceos_api = { workspace = true }
axio = "0.1"
axerrno = "0.1"
kspin = "0.1"
lock_api = { version = "0.4", default-features = false }
