[workspace]

members = [
    "apps/exception",
    "apps/helloworld",
    "apps/memtest",
    "apps/multitask",
    "apps/net/echoserver",
    "apps/net/httpclient",
    "apps/net/httpserver",

    "crates/allocator",
    "crates/crate_interface",
    "crates/driver_block",
    "crates/driver_common",
    "crates/driver_net",
    "crates/driver_virtio",
    "crates/lazy_init",
    "crates/linked_list",
    "crates/memory_addr",
    "crates/page_table",
    "crates/page_table_entry",
    "crates/ratio",
    "crates/scheduler",
    "crates/tuple_for_each",

    "modules/axalloc",
    "modules/axconfig",
    "modules/axdriver",
    "modules/axerror",
    "modules/axhal",
    "modules/axlog",
    "modules/axnet",
    "modules/axruntime",
    "modules/axtask",

    "ulib/libax",
    "ulib/c_libax/libax_bindings",
]
