[workspace]
resolver = "2"

members = [
    "crates/allocator",
    "crates/arm_gic",
    "crates/arm_pl011",
    "crates/dw_apb_uart",
    "crates/axerrno",
    "crates/axfs_devfs",
    "crates/axfs_ramfs",
    "crates/axfs_vfs",
    "crates/axio",
    "crates/capability",
    "crates/crate_interface",
    "crates/driver_block",
    "crates/driver_common",
    "crates/driver_display",
    "crates/driver_net",
    "crates/driver_pci",
    "crates/driver_virtio",
    "crates/flatten_objects",
    "crates/handler_table",
    "crates/kernel_guard",
    "crates/lazy_init",
    "crates/linked_list",
    "crates/memory_addr",
    "crates/page_table",
    "crates/page_table_entry",
    "crates/percpu",
    "crates/percpu_macros",
    "crates/ratio",
    "crates/scheduler",
    "crates/slab_allocator",
    "crates/spinlock",
    "crates/timer_list",
    "crates/tuple_for_each",
    "crates/elf_parser",

    "modules/axalloc",
    "modules/axconfig",
    "modules/axdisplay",
    "modules/axdriver",
    "modules/axfs",
    "modules/axhal",
    "modules/axlog",
    "modules/axnet",
    "modules/axruntime",
    "modules/axsync",
    "modules/axtask",
    "modules/axprocess",
    "modules/axsignal",

    "api/axfeat",
    "api/arceos_api",
    
    "api/arceos_posix_api",

    "ulib/axstd",
    "ulib/axlibc",
    "ulib/axstarry",
    "apps/display",
    "apps/exception",
    "apps/helloworld",
    "apps/memtest",
    "apps/fs/shell",
    "apps/net/echoserver",
    "apps/net/httpclient",
    "apps/net/httpserver",
    "apps/net/udpserver",
    "apps/net/bwbench",
    "apps/task/parallel",
    "apps/task/sleep",
    "apps/task/yield",
    "apps/task/priority",
    "apps/task/tls",
    "apps/monolithic_userboot"
]

[profile.release]
lto = true

[profile.dev]
lto = true

[patch.crates-io]
crate_interface = { path = "crates/crate_interface" }

[patch."https://github.com/rcore-os/smoltcp.git"]
smoltcp = { git = "https://github.com/c0per/smoltcp", branch = "starryos" }
