[workspace]

members = [
    "apps/echoserver",
    "apps/exception",
    "apps/helloworld",
    "apps/memtest",
    "apps/multitask",

    "crates/allocator",
    "crates/crate_interface",
    "crates/driver_common",
    "crates/driver_net",
    "crates/driver_virtio",
    "crates/lazy_init",
    "crates/linked_list",
    "crates/memory_addr",
    "crates/page_table",
    "crates/scheduler",
    "crates/tuple_for_each",

    "modules/axalloc",
    "modules/axconfig",
    "modules/axdriver",
    "modules/axerror",
    "modules/axhal",
    "modules/axnet",
    "modules/axruntime",
    "modules/axtask",
]
