[package]
name = "page_table_entry"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "Page table entry definition for various hardware architectures"
license = "GPL-3.0-or-later OR Apache-2.0 OR MulanPSL-2.0"
homepage = "https://github.com/arceos-org/arceos"
repository = "https://github.com/arceos-org/arceos/tree/main/crates/page_table_entry"
documentation = "https://arceos-org.github.io/arceos/page_table_entry/index.html"

[dependencies]
bitflags = "2.5"
memory_addr = { path = "../memory_addr" }
aarch64-cpu = "9.4" # TODO: put it in [target.'cfg(target_arch = "aarch64")'.dependencies]

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.15"
