[package]
name = "axtask"
version.workspace = true
edition.workspace = true
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "ArceOS task management module"
license.workspace = true
homepage.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axtask"
documentation = "https://arceos-org.github.io/arceos/axtask/index.html"

[features]
default = []

multitask = [
    "dep:axconfig",
    "dep:percpu",
    "dep:kspin",
    "dep:lazyinit",
    "dep:memory_addr",
    "dep:scheduler",
    "dep:timer_list",
    "kernel_guard",
    "dep:crate_interface",
    "dep:cpumask",
]
irq = []
tls = ["axhal/tls"]
preempt = ["irq", "percpu?/preempt", "kernel_guard/preempt"]
smp = ["kspin/smp"]

sched_fifo = ["multitask"]
sched_rr = ["multitask", "preempt"]
sched_cfs = ["multitask", "preempt"]

test = ["percpu?/sp-naive"]

[dependencies]
cfg-if = "1.0"
log = "=0.4.21"
axhal = { workspace = true }
axconfig = { workspace = true, optional = true }
percpu = { version = "0.2", optional = true }
kspin = { version = "0.1", optional = true }
lazyinit = { version = "0.2", optional = true }
memory_addr = { version = "0.3", optional = true }
timer_list = { version = "0.1", optional = true }
kernel_guard = { version = "0.1", optional = true }
crate_interface = { version = "0.1", optional = true }
cpumask = { version = "0.1", optional = true }
scheduler = { git = "https://github.com/arceos-org/scheduler.git", tag = "v0.1.0", optional = true }

[dev-dependencies]
rand = "0.8"
axhal = { workspace = true, features = ["fp_simd"] }
axtask = { workspace = true, features = ["test", "multitask"] }
