[package]
name = "axtask"
version.workspace = true
edition.workspace = true
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "ArceOS task management module"
license.workspace = true
homepage.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axtask"
documentation = "https://arceos-org.github.io/arceos/axtask/index.html"

[features]
default = []

multitask = [
    "dep:axconfig",
    "dep:axsched",
    "dep:cpumask",
    "dep:crate_interface",
    "dep:kernel_guard",
    "dep:kspin",
    "dep:lazyinit",
    "dep:memory_addr",
    "dep:percpu",
    "dep:timer_list",
]
irq = []
tls = ["axhal/tls"]
preempt = ["irq", "percpu?/preempt", "kernel_guard/preempt"]
smp = ["kspin/smp"]

sched-fifo = ["multitask"]
sched-rr = ["multitask", "preempt"]
sched-cfs = ["multitask", "preempt"]

test = ["percpu?/sp-naive"]

[dependencies]
axconfig = { workspace = true, optional = true }
axhal.workspace = true
axsched = { version = "0.3", optional = true }
cfg-if.workspace = true
cpumask = { version = "0.1", optional = true }
crate_interface = { workspace = true, optional = true }
kernel_guard = { workspace = true, optional = true }
kspin = { workspace = true, optional = true }
lazyinit = { workspace = true, optional = true }
log.workspace = true
memory_addr = { workspace = true, optional = true }
percpu = { workspace = true, optional = true }
timer_list = { version = "0.1", optional = true }

[dev-dependencies]
rand = "0.9"
axhal = { workspace = true, features = ["fp-simd"] }
axtask = { workspace = true, features = ["test", "multitask"] }
