[package]
name = "axtask"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "ArceOS task management module"
license = "GPL-3.0-or-later OR Apache-2.0"
homepage = "https://github.com/rcore-os/arceos"
repository = "https://github.com/rcore-os/arceos/tree/main/modules/axtask"
documentation = "https://rcore-os.github.io/arceos/axtask/index.html"

[features]
test = ["percpu?/sp-naive"]
multitask = [
    "dep:axconfig", "dep:percpu", "dep:spinlock", "dep:lazy_init",
    "dep:memory_addr", "dep:scheduler", "dep:timer_list"
]
irq = []
preempt = ["irq", "percpu?/preempt", "kernel_guard/preempt"]

sched_fifo = ["multitask"]
sched_rr = ["multitask", "preempt"]
sched_cfs = ["multitask", "preempt"]

# 是否使用宏内核架构
macro = []

default = ["sched_fifo", "macro"]

[dependencies]
cfg-if = "1.0"
log = "0.4"
axalloc = { path = "../axalloc", optional = true }
axhal = { path = "../axhal" }
axconfig = { path = "../axconfig", optional = true }
percpu = { path = "../../crates/percpu", optional = true }
spinlock = { path = "../../crates/spinlock", optional = true }
lazy_init = { path = "../../crates/lazy_init", optional = true }
memory_addr = { path = "../../crates/memory_addr", optional = true }
scheduler = { path = "../../crates/scheduler", optional = true }
timer_list = { path = "../../crates/timer_list", optional = true }
kernel_guard = { path = "../../crates/kernel_guard" }
crate_interface = { path = "../../crates/crate_interface" }
riscv = { path = "../../extern_crates/riscv-0.10.1" }
[dev-dependencies]
rand = "0.8"
axhal = { path = "../axhal", features = ["fp_simd"] }
axtask = { path = ".", features = ["test"] }
