[package]
name = "arceos-sleep"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
sched_rr = ["axstd/sched_rr"]

[dependencies]
axstd = { path = "../../../ulib/axstd", features = ["paging", "multitask", "irq"] }
