[package]
name = "fat32-pack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fatfs = "0.3.6"
clap = { version = "4.3.2", features = ["derive"]}

[workspace]