[package]
name = "scheduler"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "Various scheduler algorithms in a unified interface"
license = "GPL-3.0-or-later OR Apache-2.0"
homepage = "https://github.com/rcore-os/arceos"
repository = "https://github.com/rcore-os/arceos/tree/main/crates/scheduler"
documentation = "https://rcore-os.github.io/arceos/scheduler/index.html"

[dependencies]
linked_list = { path = "../linked_list" }
