[package]
name = "axnet"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["axdriver/virtio-net"]

[dependencies]
log = "0.4"
driver_net = { path = "../../crates/driver_net" }
axdriver = { path = "../axdriver" }
