[package]
name = "axdma"
edition.workspace = true
version.workspace = true
authors = ["Zhour Rui <zrufo747@outlook.com>"]
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axdma"
documentation = "https://arceos-org.github.io/arceos/axdma/index.html"

[dependencies]
allocator.workspace = true
axalloc.workspace = true
axconfig.workspace = true
axerrno.workspace = true
axhal = { workspace = true, features = ["paging"] }
axmm.workspace = true
kspin.workspace = true
log.workspace = true
memory_addr.workspace = true
