[package]
name = "axdisplay"
version.workspace = true
edition.workspace = true
authors = ["Shiping Yuan <robert_yuan@pku.edu.com>"]
description = "ArceOS graphics module"
license.workspace = true
homepage.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axdisplay"
documentation = "https://arceos-org.github.io/arceos/axdisplay/index.html"

[dependencies]
log = "=0.4.21"
lazyinit = "0.2"
axdriver = { workspace = true, features = ["display"] }
axsync = { workspace = true }
axdriver_display = { git = "https://github.com/arceos-org/axdriver_crates.git", tag = "v0.1.2" }
