[package]
name = "ext2fs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
spin = "0.7.0"
log = "0.4.0"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
fs_utils = { path = "../fs_utils" }