[package]
name = "axalloc"
version.workspace = true
edition.workspace = true
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "ArceOS global memory allocator"
license.workspace = true
homepage.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axalloc"
documentation = "https://arceos-org.github.io/arceos/axalloc/index.html"

[features]
default = ["tlsf", "allocator/page-alloc-256m"]
tlsf = ["allocator/tlsf"]
slab = ["allocator/slab"]
buddy = ["allocator/buddy"]
page-alloc-64g = [
    "allocator/page-alloc-64g",
] # Support up to 64G memory capacity
page-alloc-4g = ["allocator/page-alloc-4g"] # Support up to 4G memory capacity

[dependencies]
allocator = { workspace = true, features = ["bitmap"] }
axerrno.workspace = true
cfg-if.workspace = true
kspin.workspace = true
log.workspace = true
memory_addr.workspace = true
