# Architecture identifier.
arch = "aarch64"
# Platform identifier.
platform = "aarch64-raspi4"
# Platform family.
family = "aarch64-raspi"

# Base physical address of the kernel image.
kernel-base-paddr = "0x8_0000"
# Base virtual address of the kernel image.
kernel-base-vaddr = "0xffff_0000_0008_0000"
# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
phys-virt-offset = "0xffff_0000_0000_0000"
# MMIO regions with format (`base_paddr`, `size`).
mmio-regions = [
    ["0xFE20_1000", "0x1000"],      # PL011 UART
    ["0xFF84_1000", "0x8000"],      # GICv2
]
virtio-mmio-regions = []
# UART Address
uart-paddr = "0xFE20_1000"
uart-irq = "0x79"

# GIC Address
gicc-paddr = "0xFF84_2000"
gicd-paddr = "0xFF84_1000"

# Testcase memory
testcase-memory-start = "0x9000_0000"
testcase-memory-size = "0x800_0000"    # 如果是要手动加载进来，认为镜像大小是128MB
qemu-memory-size = "0x4000_0000"    # 如果用qemu挂载镜像，镜像大小认为是1G，但实际远小于1G
user-heap-base = "0x3F90_0000"
user-stack-top = "0x3FE0_0000"
max-user-heap-size = "0x40_0000"
max-user-stack-size = "0x20_0000"
signal-trampoline = "0x4000_0000"