[workspace]
members = ["node", "sink"]
resolver = "2"


[workspace.dependencies]
dora-node-api = "0.3.5" # { path = "../../../dora/apis/rust/node" }

[workspace.metadata.arceos]
features = ["net", "multitask"]