[package]
name = "axmm"
version.workspace = true
edition.workspace = true
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "ArceOS virtual memory management module"
license.workspace = true
homepage.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axmm"
documentation = "https://arceos-org.github.io/arceos/axmm/index.html"

[features]

[dependencies]
axalloc.workspace = true
axconfig.workspace = true
axerrno.workspace = true
axhal = { workspace = true, features = ["paging"] }
kspin.workspace = true
lazyinit.workspace = true
log.workspace = true
memory_addr.workspace = true
memory_set = { version = "0.4", features = ["axerrno"] }
