[package]
name = "embassy-user"
authors = ["nostalgia <lv15623448685@gmail.com>"]
edition.workspace = true

[dependencies]
axstd = { workspace = true, features = ["alloc","multitask"], optional = true }

embassy-futures = "0.1.1"
embassy-executor = { version = "0.7.0", features = ["nightly","executor-thread"] }
embassy-time = {version = "0.4.0", features = ["mock-driver"]}