[package]
name = "axsignal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

signal = ["axhal/signal"]

[dependencies]
numeric-enum-macro = { git = "https://github.com/mexus/numeric-enum-macro" }
bitflags = "2.0"
axhal = { path = "../axhal" }