# Architecture identifier.
arch = "unknown"
# Platform identifier.
platform = "dummy"

# Base address of the whole physical memory.
phys-memory-base = "0"
# Size of the whole physical memory.
phys-memory-size = "0"
# Base physical address of the kernel image.
kernel-base-paddr = "0"
# Base virtual address of the kernel image.
kernel-base-vaddr = "0"
# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
phys-virt-offset = "0"
# MMIO regions with format (`base_paddr`, `size`).
mmio-regions = []
# VirtIO MMIO regions with format (`base_paddr`, `size`).
virtio-mmio-regions = []

# Timer interrupt frequency.
timer_frequency = "0"
