[package]
name = "lwip_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libax = { path = "../../../ulib/libax", features = ["paging", "multitask", "net"] }
