[package]
name = "arceos-parallel"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
preempt = ["libax/sched_rr"]
default = ["libax/default"]

[dependencies]
libax = { path = "../../../ulib/libax", default_features = false, features = ["alloc", "paging", "multitask"] }
