[package]
name = "axfs"
version.workspace = true
edition.workspace = true
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "ArceOS filesystem module"
license.workspace = true
homepage.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axfs"
documentation = "https://arceos-org.github.io/arceos/axfs/index.html"

[features]
devfs = ["dep:axfs_devfs"]
ramfs = ["dep:axfs_ramfs"]
procfs = ["dep:axfs_ramfs"]
sysfs = ["dep:axfs_ramfs"]
fatfs = ["dep:fatfs"]
myfs = ["dep:crate_interface"]
use-ramdisk = []

default = ["devfs", "ramfs", "fatfs", "procfs", "sysfs"]

[dependencies]
axdriver = { workspace = true, features = ["block"] }
axdriver_block.workspace = true
axerrno.workspace = true
axfs_devfs = { version = "0.1", optional = true }
axfs_ramfs = { version = "0.1", optional = true }
axfs_vfs = "0.1"
axio = { workspace = true, features = ["alloc"] }
axns.workspace = true
axsync.workspace = true
cap_access = "0.1"
cfg-if.workspace = true
crate_interface = { workspace = true, optional = true }
lazyinit.workspace = true
log.workspace = true

[dependencies.fatfs]
git = "https://github.com/rafalh/rust-fatfs"
rev = "4eccb50"
optional = true
default-features = false
features = [ # no std
    "alloc",
    "lfn",
    "log_level_trace",
    "unicode",
]

[dev-dependencies]
axdriver = { workspace = true, features = ["block", "ramdisk"] }
axdriver_block = { workspace = true, features = ["ramdisk"] }
axsync = { workspace = true, features = ["multitask"] }
axtask = { workspace = true, features = ["test"] }
