[package]
name = "axdriver"
version.workspace = true
edition.workspace = true
authors = [
    "Yuekai Jia <equation618@gmail.com>",
    "ChengXiang Qi <kuangjux@outlook.com>",
]
description = "ArceOS device drivers"
license.workspace = true
homepage.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axdriver"
documentation = "https://arceos-org.github.io/arceos/axdriver/index.html"

[features]
bus-mmio = []
bus-pci = ["dep:axdriver_pci", "dep:axhal", "dep:axconfig"]
net = ["dep:axdriver_net"]
block = ["dep:axdriver_block"]
display = ["dep:axdriver_display"]

# Enabled by features `virtio-*`
virtio = ["dep:axdriver_virtio", "dep:axalloc", "dep:axhal", "dep:axconfig"]

# various types of drivers
virtio-blk = ["block", "virtio", "axdriver_virtio/block"]
virtio-net = ["net", "virtio", "axdriver_virtio/net"]
virtio-gpu = ["display", "virtio", "axdriver_virtio/gpu"]
ramdisk = ["block", "axdriver_block/ramdisk"]
bcm2835-sdhci = ["block", "axdriver_block/bcm2835-sdhci"]
sdmmc = ["block", "axdriver_block/sdmmc", "dep:axhal", "dep:axconfig"]
ixgbe = ["net", "axdriver_net/ixgbe", "dep:axalloc", "dep:axhal", "dep:axdma"]
fxmac = ["net", "axdriver_net/fxmac", "dep:axalloc", "dep:axhal", "dep:axdma"]
# more devices example: e1000 = ["net", "axdriver_net/e1000"]

irq = []
dyn = [
    "dep:arm-gic-driver",
    "arm-gic-driver?/rdif",
    "dep:axerrno",
    "dep:axhal",
    "dep:axklib",
    "dep:axmm",
    "dep:dma-api",
    "dep:memory_addr",
    "dep:rdif-block",
    "dep:rdif-intc",
    "dep:rdrive",
    "dep:spin",
]

default = ["bus-pci"]

[dependencies]
axalloc = { workspace = true, optional = true }
axconfig = { workspace = true, optional = true }
axdma = { workspace = true, optional = true }
axdriver_base.workspace = true
axdriver_block = { workspace = true, optional = true }
axdriver_display = { workspace = true, optional = true }
axdriver_net = { workspace = true, optional = true }
axdriver_pci = { workspace = true, optional = true }
axdriver_virtio = { workspace = true, optional = true }
axerrno = { workspace = true, optional = true }
axhal = { workspace = true, optional = true }
axklib = { workspace = true, optional = true }
axmm = { workspace = true, optional = true }
cfg-if.workspace = true
crate_interface.workspace = true
dma-api = { version = "0.5", features = ["alloc"], optional = true }
log.workspace = true
memory_addr = { workspace = true, optional = true }
rdif-block = { version = "0.6.2", optional = true }
rdif-intc = { version = "0.12", optional = true }
rdrive = { version = "0.18", optional = true }
smallvec = { version = "1.15", features = ["const_generics", "union"] }
spin = { version = "0.10", optional = true }

[target.'cfg(target_arch = "aarch64")'.dependencies]
arm-gic-driver = { version = "0.15", optional = true }
