[package]
name = "spinlock"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
std = ["smp"]
smp = []
default = []

[dependencies]
cfg-if = "1.0"
crate_interface = { path = "../crate_interface" }
