name: Download and build QEMU

inputs:
  qemu-version:
    description: 'QEMU version'
    required: true
    type: string

runs:
  using: "composite"
  steps:
  - name: Cache QEMU
    id: cache-qemu
    uses: actions/cache/restore@v4
    with:
      path: qemu_build
      key: qemu-${{ inputs.qemu-version }}-slirp-1
  - name: Download and build QEMU
    if: steps.cache-qemu.outputs.cache-hit != 'true'
    env:
      QEMU_PATH: qemu-${{ inputs.qemu-version }}
      PREFIX: ${{ github.workspace }}/qemu_build
    shell: bash
    run: |
      sudo apt-get update && sudo apt-get install -y ninja-build libslirp-dev libglib2.0-dev
      wget https://download.qemu.org/$QEMU_PATH.tar.xz && tar -xJf $QEMU_PATH.tar.xz
      cd $QEMU_PATH \
        && ./configure --prefix=$PREFIX --target-list=x86_64-softmmu,riscv64-softmmu,aarch64-softmmu,loongarch64-softmmu --enable-slirp \
        && make -j > /dev/null 2>&1 \
        && make install
  - uses: actions/cache/save@v4
    if: steps.cache-qemu.outputs.cache-hit != 'true'
    with:
      path: qemu_build
      key: qemu-${{ inputs.qemu-version }}-slirp-1

  - name: Install QEMU
    shell: bash
    run: |
      echo "$PWD/qemu_build/bin" >> $GITHUB_PATH
  - name: Verify installation
    shell: bash
    run: |
      qemu-system-x86_64 --version
      qemu-system-aarch64 --version
      qemu-system-riscv64 --version
      qemu-system-loongarch64 --version
